{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-7.0.6.jar",
          "url": "spring-aspects-7.0.6.jar",
          "size": 50031,
          "sha512": "b0ed24c0eeea1d0006236c713cfb54b9e1522efe99abf9773b035e2c24faa5491e91a97a79a1ced9805b4b9c392539df256f6f3161c0179c3f74248ec3baaf41",
          "sha256": "a1a6a6af6ae3f0a8bcc1db94025542233f43fc9b3daec8a21b01ae4fe001c850",
          "sha1": "5a89bac97d1aa057aa9bafc1cd1c76b1329dc0cc",
          "md5": "20029a9c70b1111228e228674ef9731b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.25"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjtools"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-aspects-7.0.6.jar",
          "url": "spring-aspects-7.0.6.jar",
          "size": 50031,
          "sha512": "b0ed24c0eeea1d0006236c713cfb54b9e1522efe99abf9773b035e2c24faa5491e91a97a79a1ced9805b4b9c392539df256f6f3161c0179c3f74248ec3baaf41",
          "sha256": "a1a6a6af6ae3f0a8bcc1db94025542233f43fc9b3daec8a21b01ae4fe001c850",
          "sha1": "5a89bac97d1aa057aa9bafc1cd1c76b1329dc0cc",
          "md5": "20029a9c70b1111228e228674ef9731b"
        }
      ]
    }
  ]
}
